name: Pull and  Push c 0.2 to Aliyun ACR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pull-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Aliyun ACR
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.ALIYUN_REGISTRY }}
        username: ${{ secrets.ALIYUN_USERNAME }}
        password: ${{ secrets.ALIYUN_PASSWORD }}

    - name: Pull Apache jupyter Image 0.2
      run: docker pull --platform=linux/arm64 jupyter/base-notebook:notebook-7.0.6

    - name: Tag Apache tdsql Image for Aliyun ACR
      run: |
        docker tag jupyter/base-notebook:notebook-7.0.6 ${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAMESPACE }}/lanres:0.2

    - name: Push jupyter Image 0.2 to Aliyun ACR
      run: docker push ${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAMESPACE }}/lanres:0.2
