name: Pull and  Push Apache Zeppelin 0.12.0 to Aliyun ACR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pull-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Aliyun ACR
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.ALIYUN_REGISTRY }}
        username: ${{ secrets.ALIYUN_USERNAME }}
        password: ${{ secrets.ALIYUN_PASSWORD }}

    - name: Pull Apache Zeppelin Image 0.12.0
      run: docker pull apache/zeppelin:0.12.0

    - name: Tag Apache Zeppelin Image for Aliyun ACR
      run: |
        docker tag apache/zeppelin:0.12.0 ${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAMESPACE }}/lanres:0.12.0

    - name: Push Apache Zeppelin Image 0.12.0 to Aliyun ACR
      run: docker push ${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAMESPACE }}/lanres:0.12.0
