---
name: Pull x86 Image and Sync to ACR
on:
  workflow_dispatch: null
jobs:
  sync-image:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取x86架构的nginx镜像
        run: >
          docker pull --platform linux/amd64 nginx:latest

          docker tag nginx:latest ${{ SSS.ALIYUN_REGISTRY }}/${{ SSS.ALIYUN_NAME_SPACE }}/nginx:x86-latest
      - name: 登录阿里云ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ SSS.ALIYUN_REGISTRY }}
          username: ${{ SSS.ALIYUN_REGISTRY_USER }}
          password: ${{ SSS.ALIYUN_REGISTRY_PASSWORD }}
      - name: 推送镜像到ACR
        run: >
          docker push ${{ SSS.ALIYUN_REGISTRY }}/${{ SSS.ALIYUN_NAME_SPACE
          }}/nginx:x86-latest
